### ISSUE TITLE
[BUG] Player viewbox moves around when switching scenes, does not respect scene boundary

### ISSUE THREAD

**Issue by AnthonyEdmonds** [MaterialFoundry/LockView#135]
**Setup**

 - OS: Windows 11
 - Browser: Foundry Chrome
 - Module version: 2.x
 - Foundry version: 13.x
 - Gaming system & version: Generic worldbuilding
 - Any other modules enabled: Yes

**Describe the bug**

I have two scenes, neither of which have "Force intial view" enabled.

Both have autoscaling to physical grid size enabled.

1. With the viewbox correctly positioned on the first scene...
2. ... switching to the second scene causes the viewbox to jump, usually out of bounds
3. Moving the viewbox on the second scene will now cause the issue to occur...
4. ... when switching to the first scene.

I would expect both scenes to remain where placed, with no interaction between the two scenes.

**Screenshots**

![Image](https://github.com/user-attachments/assets/d54fc388-3640-4e1d-bb29-731195e087a1)

**Console Log**

Console is clear of errors.

**Comment by MaterialFoundry** [comment]
If I understood your issue correctly, it should be fixed in v2.0.1 which was just released.

**Comment by AnthonyEdmonds** [comment]
Hi, I meant to reply to this sooner, but you know how life is.

The issue persists, and I thought it might be easier to demonstrate the problem with a video: https://youtu.be/y2Xe03YinwQ

You'll have to forgive the potato quality; I haven't had OBS set up for a long time.

Essentially:

1. Moving the player's viewbox causes it to move in all scenes
2. Moving the player's viewbox on a large scene causes it to go out of bounds on another scene

All scenes shown in the video are set to autoscale to physical gridsize, but not to force the initial view.
